### PR TITLE
Bump drizzle

### PR DESCRIPTION
**Pull request by erikjung**
This should bring in the new demo thumbnails.

### CODE REVIEW

**Comment by tylersticka** [comment]
_Just submitted cloudfour/drizzle#25 _ 😬

**Comment by tylersticka** [comment]
_Merges PR..._

@erikjung Wanna, ermm, update again? 😅

**Comment by erikjung** [comment]
@tylersticka It's all set.

**Comment by tylersticka** [comment]
Thanks, @erikjung ! Updated the generator locally, everything worked swimmingly. LGTM 👍

**Pull request merged**
