### PR TITLE
Feature: add Drizzle submodule

### PR DESCRIPTION
**Pull request by erikjung**
This makes the generator actually function as a Drizzle project starter.

To test this, follow the same steps described here: https://github.com/cloudfour/generator-drizzle/pull/1

### CODE REVIEW

**Comment by tylersticka** [comment]
Hmm, this didn't really work for me as is. I followed the instructions in #1, and this was the output:

```
$ yo drizzle

Welcome to your new Drizzle project.
Setup phase starting...

? Title Untitled Drizzle Project
? Description Holla
   create .github/ISSUE_TEMPLATE.md
   create .github/PULL_REQUEST_TEMPLATE.md
   create README.md

Setup phase completed.
```

But then when I tried running `npm start`:

```
$ npm start
npm ERR! Darwin 15.4.0
npm ERR! argv "/opt/nodes/4.0.0/bin/node" "/opt/boxen/nodenv/versions/4.0.0/bin/npm" "start"
npm ERR! node v4.0.0
npm ERR! npm  v3.5.0
npm ERR! path /Users/tylersticka/src/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/Users/tylersticka/src/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/Users/tylersticka/src/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tylersticka/src/dummy-project/npm-debug.log
```

And the directory only includes the files from the `create` output (plus `npm-debug.log` due to the aforementioned errors).

**Comment by erikjung** [comment]
@tylersticka Can you try going to the `generator-drizzle` working copy and running `git submodule init`?

**Comment by mrgerardorodriguez** [comment]
I'm getting the same thing as @tylersticka, FWIW. Trying the `git submodule init` now.

**Comment by tylersticka** [comment]
@erikjung No change for me after I run that command.

Here was the command's output, in case that's helpful:

```
~/src/generator-drizzle feat-add_drizzle_submodule
❯ git submodule init
Submodule 'generators/app/templates/drizzle' (https://github.com/cloudfour/drizzle.git) registered for path 'generators/app/templates/drizzle'
```

I also tried running `npm link` again in `generator-drizzle` to see if that made any difference (it didn't seem to).

**Comment by erikjung** [comment]
@tylersticka @mrgerardorodriguez 

My mistake, 

```
git submodule init
git submodule update
```

**Comment by mrgerardorodriguez** [comment]
@erikjung It worked! 😀

**Comment by tylersticka** [comment]
@erikjung Working for me too, I assume (`npm install` is still running).

Is there any way to bake that stuff into a shortcut task to make installing the generator easier?

**Comment by tylersticka** [comment]
@erikjung Finished installing, seems to be working.

(FYI, the version of the "demos" page it pulled lacks the thumbnail stuff I did recently. So cloudfour/drizzle may need a new version or something. If this is something I can help with, feel free to assign an issue to me.)

**Comment by erikjung** [comment]
> Is there any way to bake that stuff into a shortcut task to make installing the generator easier?

@tylersticka Once it's published on npm, the submodule commands won't be needed. The setup will be simply:

```
npm install -g generator-drizzle
yo drizzle
```

**Comment by mrgerardorodriguez** [comment]
Code LGTM 👍

**Comment by erikjung** [comment]
Going to merge this and then make sure everything is updated (in regards to Drizzle stuff).

**Pull request merged**
